<?php
/**
 * Export and import alert settings.
 *
 * @package WP_Stream
 */

namespace WP_Stream;

/**
 * Class - Alert_Port
 *
 * Serializes configured alert rules to JSON and imports them back,
 * so settings can be cloned across installs.
 */
class Alert_Port {

	/**
	 * Export file format version. Bump if the payload shape changes.
	 */
	const FORMAT_VERSION = 1;

	/**
	 * Generator string written into the export header.
	 */
	const GENERATOR = 'WP Stream';

	/**
	 * Export action / nonce name.
	 */
	const EXPORT_ACTION = 'wp_stream_alert_port_export';

	/**
	 * Import action / nonce name.
	 */
	const IMPORT_ACTION = 'wp_stream_alert_port_import';

	/**
	 * Query arg used to pass the import result back to the alerts screen.
	 */
	const RESULT_ARG = 'wp_stream_alert_port_result';

	/**
	 * Holds instance of plugin object
	 *
	 * @var Plugin
	 */
	public $plugin;

	/**
	 * Class constructor
	 *
	 * @param Plugin $plugin The plugin object.
	 */
	public function __construct( $plugin ) {
		$this->plugin = $plugin;

		// Download + upload handlers self-gate on capability and nonce,
		// so they are safe to register on every request.
		add_action( 'admin_init', array( $this, 'handle_export' ) );
		add_action( 'admin_post_' . self::IMPORT_ACTION, array( $this, 'handle_import' ) );

		// UI + result notices only belong on the alerts list screen.
		if ( $this->is_alerts_screen() ) {
			add_filter( 'views_edit-wp_stream_alerts', array( $this, 'render_controls' ) );
			add_action( 'admin_notices', array( $this, 'render_result_notice' ) );
		}
	}

	/**
	 * Whether the current request is the alerts list screen.
	 *
	 * Checked via the request's post_type so it is available during admin_init,
	 * before get_current_screen() is populated.
	 *
	 * @return bool
	 */
	protected function is_alerts_screen() {
		return Alerts::POST_TYPE === wp_stream_filter_input( INPUT_GET, 'post_type' );
	}

	/**
	 * Build the export payload from all configured alerts.
	 *
	 * Kept separate from the download handler so tests can call it directly
	 * without dealing with headers and exit.
	 *
	 * @return array
	 */
	public function get_export_data() {
		$alerts = $this->plugin->alerts->get_alerts();

		$rows = array();
		foreach ( $alerts as $alert ) {
			// ID, date, author and title are site-local or regenerated by
			// Alert::save(), so they are intentionally not exported. All
			// alert_meta keys are preserved verbatim; third-party notifiers
			// extend alert_meta via the wp_stream_alerts_save_meta filter.
			$rows[] = array(
				'status'     => $alert->status,
				'alert_type' => $alert->alert_type,
				'alert_meta' => $alert->alert_meta ? (array) $alert->alert_meta : array(),
			);
		}

		/**
		 * Filter the alert export payload before it is encoded.
		 *
		 * @param array $data Export payload including the header and alerts array.
		 */
		return apply_filters(
			'wp_stream_alert_export_data',
			array(
				'generator' => self::GENERATOR,
				'version'   => self::FORMAT_VERSION,
				'alerts'    => $rows,
			)
		);
	}

	/**
	 * Send the export file as a JSON download.
	 *
	 * @return void
	 */
	public function handle_export() {
		if ( ! current_user_can( Alerts::CAPABILITY ) ) {
			return;
		}

		$nonce = wp_stream_filter_input( INPUT_GET, '_wpnonce' );
		if ( ! wp_verify_nonce( $nonce, self::EXPORT_ACTION ) ) {
			return;
		}

		$data = $this->get_export_data();

		if ( ! defined( 'WP_STREAM_TESTS' ) || ( defined( 'WP_STREAM_TESTS' ) && ! WP_STREAM_TESTS ) ) {
			nocache_headers();
			header( 'Content-Type: application/json; charset=' . get_option( 'blog_charset' ) );
			header( 'Content-Disposition: attachment; filename="stream-alerts.json"' );
		}

		echo wp_json_encode( $data ); // @codingStandardsIgnoreLine download output

		if ( ! defined( 'WP_STREAM_TESTS' ) || ( defined( 'WP_STREAM_TESTS' ) && ! WP_STREAM_TESTS ) ) {
			exit;
		}
	}

	/**
	 * Import alerts from an uploaded JSON file.
	 *
	 * @return void
	 */
	public function handle_import() {
		if ( ! current_user_can( Alerts::CAPABILITY ) ) {
			wp_die( esc_html__( 'You do not have permission to import alert settings.', 'stream' ) );
		}

		check_admin_referer( self::IMPORT_ACTION );

		if ( empty( $_FILES['import_file'] ) ) {
			$this->redirect_result( 'error', __( 'No file was uploaded.', 'stream' ) );
			return;
		}

		// wp_handle_upload needs the file array passed by reference.
		$file = $_FILES['import_file']; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.MissingUnslash,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- validated via wp_handle_upload below.

		$upload = wp_handle_upload(
			$file,
			array(
				'test_form' => false,
				'mimes'     => array(
					'json' => 'application/json',
				),
			)
		);

		if ( isset( $upload['error'] ) ) {
			$this->redirect_result( 'error', $upload['error'] );
			return;
		}

		$contents = file_get_contents( $upload['file'] ); // @codingStandardsIgnoreLine local uploaded file, cleaned up below.
		wp_delete_file( $upload['file'] );

		$payload = json_decode( $contents, true );

		if ( ! is_array( $payload ) || empty( $payload['alerts'] ) || ! is_array( $payload['alerts'] ) ) {
			$this->redirect_result( 'error', __( 'The file does not contain valid alert settings.', 'stream' ) );
			return;
		}

		$result = $this->import_alerts( $payload['alerts'] );

		$this->redirect_result(
			'imported',
			sprintf( '%d;%d', $result['imported'], $result['skipped'] )
		);
	}

	/**
	 * Redirect back to the alerts screen carrying an import result.
	 *
	 * The value is stored under a single query arg that the result notice
	 * reads back. add_query_arg() handles URL-encoding.
	 *
	 * @param string $type  Result type: 'error' or 'imported'.
	 * @param string $value Result payload, format depends on $type.
	 * @return void
	 */
	protected function redirect_result( $type, $value ) {
		wp_safe_redirect(
			add_query_arg(
				self::RESULT_ARG,
				$type . ':' . $value,
				$this->alerts_screen_url()
			)
		);
		exit;
	}

	/**
	 * Create alerts from a decoded import payload.
	 *
	 * Each valid entry is appended as a new alert. Entries with an unknown
	 * alert_type or a trigger_author pointing at a missing user are skipped
	 * or sanitized rather than aborting the whole import.
	 *
	 * @param array $alerts List of alert entry arrays.
	 * @return array {
	 *     @type int $imported Number of alerts created.
	 *     @type int $skipped  Number of entries skipped.
	 * }
	 */
	public function import_alerts( array $alerts ) {
		$registered_types = isset( $this->plugin->alerts->alert_types )
			? array_keys( (array) $this->plugin->alerts->alert_types )
			: array();

		$imported = 0;
		$skipped  = 0;

		foreach ( $alerts as $entry ) {
			if ( ! is_array( $entry ) || empty( $entry['alert_type'] ) || ! is_scalar( $entry['alert_type'] ) ) {
				++$skipped;
				continue;
			}

			$alert_type = (string) $entry['alert_type'];

			// Skip alert types the target install does not know about
			// (e.g. a notifier provided by a plugin that is not active here).
			if ( ! empty( $registered_types ) && ! in_array( $alert_type, $registered_types, true ) ) {
				++$skipped;
				continue;
			}

			$alert_meta = isset( $entry['alert_meta'] ) && is_array( $entry['alert_meta'] )
				? $entry['alert_meta']
				: array();

			// trigger_author is a user ID. Across sites the ID will not match,
			// so reset it to "any user" when the user does not exist locally
			// instead of silently binding the alert to the wrong account.
			if ( isset( $alert_meta['trigger_author'] ) ) {
				$author_id = $alert_meta['trigger_author'];
				if ( '' !== $author_id && ( ! is_numeric( $author_id ) || ! get_userdata( (int) $author_id ) ) ) {
					$alert_meta['trigger_author'] = '';
				}
			}

			$status = isset( $entry['status'] ) && Alerts::STATUS_ENABLED === $entry['status']
				? Alerts::STATUS_ENABLED
				: Alerts::STATUS_DISABLED;

			$item = (object) array(
				'status'     => $status,
				'alert_type' => $alert_type,
				'alert_meta' => $alert_meta,
			);

			$alert = new Alert( $item, $this->plugin );
			$saved = $alert->save();

			if ( $saved && ! is_wp_error( $saved ) ) {
				++$imported;
			} else {
				++$skipped;
			}
		}

		return array(
			'imported' => $imported,
			'skipped'  => $skipped,
		);
	}

	/**
	 * Render the Export link and Import form on the alerts list screen.
	 *
	 * @filter views_edit-wp_stream_alerts
	 *
	 * @param array $views View links HTML.
	 * @return array
	 */
	public function render_controls( $views ) {
		$export_url = wp_nonce_url(
			add_query_arg( self::EXPORT_ACTION, '1', $this->alerts_screen_url() ),
			self::EXPORT_ACTION
		);

		ob_start();
		?>
		<li class="wp-stream-alert-port">
			<a class="button button-small" href="<?php echo esc_url( $export_url ); ?>">
				<?php esc_html_e( 'Export', 'stream' ); ?>
			</a>
			<form method="post" enctype="multipart/form-data" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline;">
				<?php wp_nonce_field( self::IMPORT_ACTION ); ?>
				<input type="hidden" name="action" value="<?php echo esc_attr( self::IMPORT_ACTION ); ?>" />
				<input type="file" name="import_file" accept="application/json,.json" required />
				<button type="submit" class="button button-small">
					<?php esc_html_e( 'Import', 'stream' ); ?>
				</button>
			</form>
			<span class="description">
				<?php esc_html_e( 'Import adds alerts; it does not replace existing ones.', 'stream' ); ?>
			</span>
		</li>
		<?php
		$views['wp_stream_alert_port'] = ob_get_clean();

		return $views;
	}

	/**
	 * Show the import result as an admin notice.
	 *
	 * @action admin_notices
	 *
	 * @return void
	 */
	public function render_result_notice() {
		$raw = wp_stream_filter_input( INPUT_GET, self::RESULT_ARG );
		if ( null === $raw || '' === $raw ) {
			return;
		}

		// The value was written by this plugin, but it travels through a URL
		// so treat it as untrusted on read.
		$parts = explode( ':', (string) $raw, 2 );
		$type  = isset( $parts[0] ) ? $parts[0] : '';
		$value = isset( $parts[1] ) ? $parts[1] : '';

		if ( 'error' === $type ) {
			$message = '' !== $value ? $value : __( 'Import failed.', 'stream' );
			wp_admin_notice(
				'<strong>' . esc_html__( 'Alert import', 'stream' ) . ':</strong> ' . esc_html( $message ),
				array(
					'type'        => 'error',
					'dismissible' => true,
				)
			);
			return;
		}

		if ( 'imported' === $type ) {
			list( $imported, $skipped ) = $this->parse_import_counts( $value );

			$message = sprintf(
				/* translators: 1: number of alerts imported, 2: number of alerts skipped */
				_n(
					'Imported %1$d alert (%2$d skipped).',
					'Imported %1$d alerts (%2$d skipped).',
					$imported,
					'stream'
				),
				$imported,
				$skipped
			);

			wp_admin_notice(
				'<strong>' . esc_html__( 'Alert import', 'stream' ) . ':</strong> ' . esc_html( $message ),
				array(
					'type'        => 'success',
					'dismissible' => true,
				)
			);
		}
	}

	/**
	 * Parse the "imported;skipped" counts from a result value.
	 *
	 * @param string $value Result value from the redirect query arg.
	 * @return array {
	 *     @type int $0 Number imported.
	 *     @type int $1 Number skipped.
	 * }
	 */
	protected function parse_import_counts( $value ) {
		$parts    = explode( ';', (string) $value );
		$imported = isset( $parts[0] ) ? (int) $parts[0] : 0;
		$skipped  = isset( $parts[1] ) ? (int) $parts[1] : 0;

		return array( $imported, $skipped );
	}

	/**
	 * URL of the alerts list screen.
	 *
	 * @return string
	 */
	protected function alerts_screen_url() {
		return admin_url( 'edit.php?post_type=' . Alerts::POST_TYPE );
	}
}
